default: &default
  adapter: postgresql
  pool: 10
  timeout: 5000

development:
  <<: *default
  database: atrr_json_associations_development

test:
  <<: *default
  database: atrr_json_associations_test
  <% if ENV['CI'] %>
  host: localhost
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  <% end %>

production:
  <<: *default
  database: atrr_json_associations_production
